name: mooc
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - seaborn
  - tqdm
  - jupyterlab
  - tensorflow  
  - ca-certificates
  - certifi
  - openssl
  - ipywidgets
  - scikit-learn
  - pydot